# Generated by Django 5.1.4 on 2024-12-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ecosistema')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Ecosistema')),
                ('area', models.FloatField(verbose_name='Área en km²')),
                ('ubicacion', models.TextField(blank=True, null=True, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
